from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi import HTTPException
from sqlmodel import Field, Session, SQLModel, create_engine, select

# 1. Define the SQL Table & Data Bouncer in one!
class DailyEntry(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    item_name: str
    calories: int
    protein_g: float
    water_ml: int

# 2. Configure the local SQLite Database
sqlite_file_name = "database.db"
sqlite_url = f"sqlite:///{sqlite_file_name}"

# The "engine" is the actual machine that talks to the SQL database
engine = create_engine(sqlite_url, echo=True)

@asynccontextmanager
async def lifespan(app: FastAPI):
    SQLModel.metadata.create_all(engine)
    yield

app = FastAPI(lifespan=lifespan)

@app.get("/")
def read_root():
    return {"message": "Welcome to the Cloud Deployment API!"}

@app.get("/health")
def health_check():
    return {"status": "healthy"}


# CREATE Route (POST): Add a new entry to the database
@app.post("/log", response_model=DailyEntry)
def add_entry(entry: DailyEntry):
    with Session(engine) as session:
        # We tell the database session to add this verified Pydantic object
        session.add(entry)
        # We 'commit' to actually save the data to the hard drive
        session.commit()
        # We refresh so Python gets the new ID generated by SQLite
        session.refresh(entry)
        return entry

# READ Route (GET): See all entries
@app.get("/log")
def get_daily_log():
    with Session(engine) as session:
        # SQL equivalent of 'SELECT * FROM dailyentry'
        statement = select(DailyEntry)
        results = session.exec(statement).all()
        return results
    
@app.get("/log/summary")
def get_daily_summary():
    with Session(engine) as session:
        results = session.exec(select(DailyEntry)).all()
        
        total_calories = sum(item.calories for item in results)
        total_protein = sum(item.protein_g for item in results)
        total_water = sum(item.water_ml for item in results)
        
        return {
            "total_calories": total_calories,
            "total_protein_g": total_protein,
            "total_water_ml": total_water
        }
    
@app.delete("/log/{entry_id}")
def delete_entry(entry_id: int):
    with Session(engine) as session:
        # Find the specific entry first
        entry = session.get(DailyEntry, entry_id)
        if not entry:
            raise HTTPException(status_code=404, detail="Entry not found")
        
        # Tell the session to delete it and save the change
        session.delete(entry)
        session.commit()
        return {"ok": True, "message": f"Deleted entry {entry_id}"}
    
    